version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "actions/*"
      hashicorp:
        patterns:
          - "hashicorp/*"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    groups:
      cloudflare:
        patterns:
          - "cloudflare/*"
      github:
        patterns:
          - "integrations/*"
